### ISSUE TITLE
Incorrect highlighting when JSON contains comment start sequence in string

### ISSUE THREAD

**Issue by acanthite** [BlueBoxWare/LibGDXPlugin#24] opened 2020-12-01 18:08 UTC
I was trying to make some kind of index file, where I could specify whilch paths to ignore and whilch to add to processing. When I wrote some JSON to try it, editor started to highlight it in a weird way. Here is an example:
```
{
    exclude: ["test/**"]
    include: ["other/**"]
    test: ["*/some"]
}
```
This is what it looks like in Intellij:
![image](https://user-images.githubusercontent.com/52529496/100778810-2a603000-3410-11eb-8512-514100460a4f.png)
After the /* characters in the first field, highlighting breaks until editor reaches */ in the third field. It looks like it partialy understands it as multiline comment (the text became italic and squre brackets became gray).

**Comment by BlueBoxWare** [comment] 2020-12-04 13:32
The problem is that after adding a closing quote, making it a normal string, the code doesn't get fully re-parsed and the old, now wrong, highlighting remains until the next re-parse. Thanks for the notice, I'm working on a fix.

**Comment by BlueBoxWare** [comment] 2020-12-07 16:34
It will be fixed in the next update.

**Closed** 2020-12-07 16:34 UTC
